apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-web-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maheshrajannan/argocd-kustomize-example   # your repo
    targetRevision: main
    path: overlays/dev          # <-- ArgoCD points at the OVERLAY, never the base
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-dev
  syncPolicy:
    automated:
      prune: true        # delete what's no longer in Git
      selfHeal: true     # dev: auto-revert manual drift immediately
    syncOptions:
      - CreateNamespace=true
